<?php
$categories = 
        ["APPLIANCES, LARGE", 
        "APPLIANCES, SMALL", 
        "ART SUPPLIES", 
        "BEDDING / BATH", 
        "BIKES / SPORTING / CAMPING", 
        "BOOKS", 
        "BROWN PAPER / LARGE SHOPPING BAGS", 
        "BLDG MATERIALS / HOME IMPROVEMENT", 
        "CDs, DVDs, LPs, video games, etc.", 
        "CELL PHONES (preferably with chargers)", 
        "CHILDREN'S GOODS / CLOTHING", 
        "CLOTHING / ACCESSORIES ", 
        "COMPUTER PAPER  (ok if printed on one side)", 
        "COMPUTERS / MONITORS", 
        "EGG CARTONS", 
        "EYEGLASSES", 
        "FABRIC (material, batting, supplies)", 
        "FIREWOOD", 
        "FOOD (unopened, pre-expired)", 
        "FOOD (surplus garden produce)", 
        "FOOD CONTAINERS (clean glass/plastic w/lids)", 
        "FURNITURE", 
        "GARDEN / LANDSCAPING", 
        "GARDEN POTS ", 
        "HOME ELECTRONICS", 
        "HOUSEHOLD GOODS", 
        "MEDICAL EQUIPMENT / SUPPLIES", 
        "OFFICE EQUIPMENT", 
        "OFFICE SUPPLIES", 
        "PACKING MATERIALS", 
        "PET SUPPLIES / FOOD", 
        "PRINTER CARTRIDGE REFILLING", 
        "SCHOOL SUPPLIES", 
        "TOILETRIES", 
        "VEHICLES / PARTS"];
?>